---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: speed
  hostPath:
    path: "/mnt/data/mysql"


# kubectl apply -f mysql-pv.yml