---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # Permet à PrestaShop de se connecter via le DNS interne

# kubectl apply -f mysql-service.yml
