---

apiVersion: v1
kind: Service
metadata:
  name: prestashop
spec:
  type: LoadBalancer
  selector:
    app: prestashop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


# kubectl apply -f prestashop-service.yml 
