---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prestashop-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: low
  hostPath:
    path: "/mnt/data/prestashop"


# kubectl apply -f prestashop-pv.yml
