---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prestashop-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: low


# kubectl apply -f prestashop-pvc.yml
